name: Package for Linux
description: Create Debian packages for Prism Launcher

inputs:
  version:
    description: Launcher version
    required: true
  build-type:
    description: Type for the build
    required: true
    default: Debug
  artifact-name:
    description: Name of the uploaded artifact
    required: true
    default: Linux

runs:
  using: composite

  steps:
    - name: Setup package architecture
      shell: bash
      run: |
        case "$(dpkg-architecture -q DEB_HOST_ARCH)" in
          amd64)
            DEB_ARCH="x86_64"
            ;;
          arm64)
            DEB_ARCH="aarch64"
            ;;
          *)
            echo "# 🚨 The Debian architecture is not recognized!" >> "$GITHUB_STEP_SUMMARY"
            exit 1
            ;;
        esac
        echo "DEB_ARCH=$DEB_ARCH" >> "$GITHUB_ENV"

    - name: Package Debian package
      shell: bash
      run: |
        cpack --config build/CPackConfig.cmake -C "${{ inputs.build-type }}" -B build
        mv build/PrismLauncher-*.deb "PrismLauncher-Linux-${DEB_ARCH}.deb"

    - name: Upload Debian package
      uses: actions/upload-artifact@v7
      with:
        name: PrismLauncher-${{ inputs.artifact-name }}-DEB-${{ inputs.version }}-${{ inputs.build-type }}-${{ env.DEB_ARCH }}
        path: PrismLauncher-Linux-${{ env.DEB_ARCH }}.deb
